name: Build on Windows
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install MSIX Packaging Tool
        env:
            MSIX_PACKAGING_TOOL_INSTALLTION_FILE_URL: ${{env.MSIX_PACKAGING_TOOL_INSTALLTION_FILE_URL}}
            MSIX_PACKAGING_TOOL_LICENSE_FILE_URL: ${{env.MSIX_PACKAGING_TOOL_LICENSE_FILE_URL}}
        shell: pwsh
        run: .\scripts\Install-MsixPackagingTool.ps1 -MSIXPackagingToolInstallationFileUrl $env:MSIX_PACKAGING_TOOL_INSTALLTION_FILE_URL -MSIXPackagingToolLicenseFileUrl $env:MSIX_PACKAGING_TOOL_LICENSE_FILE_URL
